version: "3.4"
services:
  app:
    container_name: server
    restart: always
    build: .
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
