version: "3"
services:
  app:
    container_name: server
    restart: always
    build: .
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: mysql-movie
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"
